# Generated by Django 5.2.6 on 2025-09-24 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='imgUrl',
            field=models.CharField(default='https', max_length=255),
            preserve_default=False,
        ),
    ]
