# Generated by Django 5.0.8 on 2025-09-04 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
        ('recommendations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendationsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='foods.food'),
        ),
        migrations.AddField(
            model_name='sessionitem',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recommendations.recommendationsession'),
        ),
        migrations.AlterUniqueTogether(
            name='sessionitem',
            unique_together={('session', 'food')},
        ),
    ]
