# Generated by Django 5.2.6 on 2025-10-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionitem',
            name='predicted_rating',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
