# Generated by Django 5.2.7 on 2025-10-17 10:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0003_sessionitem_predicted_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessionitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
